# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      TZ: Asia/Seoul
